# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hn-jobs-chat',
                'doc_host': 'https://Jon-Biz.github.io',
                'git_url': 'https://github.com/Jon-Biz/hn-jobs-chat',
                'lib_path': 'hn_jobs_chat'},
  'syms': {'hn_jobs_chat.core': {'hn_jobs_chat.core.foo': ('core.html#foo', 'hn_jobs_chat/core.py')}}}
