# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_chatbot/0x_chatbot.ipynb.

# %% auto 0
__all__ = ['getResponse']

# %% ../nbs/09_chatbot/0x_chatbot.ipynb 4
from .requirements import getRequirements, requirementResponse
from .search import search
from .chat import getChatResponse

def getResponse(input:str) -> str:

    # Parse the user's last comment into the current requirements
    requirements: requirementResponse = getRequirements(input)
    currentRequirements = getCurrentRequirements(requirements)
    searchResults = search(currentRequirements)
    response = getChatResponse(input, currentRequirements, searchResults)

    return response
    
