# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_initial_exploration/00_scrape_previous.ipynb.

# %% auto 0
__all__ = ['urls', 'dataLocation']

# %% ../nbs/00_initial_exploration/00_scrape_previous.ipynb 1
urls = [    
    ["July","https://news.ycombinator.com/item?id=36573871"],
    ["June", "https://news.ycombinator.com/item?id=36152014"],
    ["May", "https://news.ycombinator.com/item?id=35773707"],
]

dataLocation = "previousData/"

