# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_pipeline-scrape/03_parse_data.ipynb.

# %% auto 0
__all__ = ['extract_middle_json', 'extractJSON']

# %% ../nbs/03_pipeline-scrape/03_parse_data.ipynb 6
import json


def extract_middle_json(response):
    # Split the string on '```'
    parts = response.split('```')
    # Select the middle portion and remove 'json' from the front
    return parts[1].replace('json', '').strip() if len(parts) > 1 else ''

def extractJSON(response):
    jsonStr = extract_middle_json(response)

    try:
        result = json.loads(jsonStr)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        print(jsonStr)

        return None

    return result
    
