# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_parameters_and_eval/getKeys.ipynb.

# %% auto 0
__all__ = ['keys', 'described_keys']

# %% ../nbs/01_parameters_and_eval/getKeys.ipynb 4
keys = [
    'company',
    'location',
    'timezone',
    'industry',
    'target_market',
    'company_status',
    'company_description',
    'company_goal',
    'company_stage',
    'more_company_info',
    'employment_type',
    'remote_or_local_details',
    'job_title',
    'job_description',
    'job_requirements',
    'job_soft_skills',
    'product_description',
    'tech_stack',
    'application_process',
    'contact_email',
    'application_url',
    'information_urls',
    'additional_notes',
    'compensation',
]

# %% ../nbs/01_parameters_and_eval/getKeys.ipynb 5
# We add a description to each key to help the LLM understand what each key is for
described_keys = [
    {'key': 'company', 'description': 'name of the company', 'type': 'string'},
    {'key': 'location', 'description': 'country, city or location otherwise stated', 'type': 'string'},
    {'key': 'timezone', 'description': 'timezones that are referred to in the job post, if any', 'type': 'string'},
    {'key': 'industry', 'description': 'the industry vertical that the company is part of', 'type': 'string'},
    {'key': 'target_market', 'description': 'the type of consumer or businesses that are targeted by the company venture', 'type': 'string'},
    {'key': 'company_status', 'description': 'the current situation that company is in', 'type': 'string'},
    {'key': 'company_description', 'description': 'description of the company, as described in the job post', 'type': 'string'},
    {'key': 'company_goal', 'description': 'primary focus of the company', 'type': 'string'},
    {'key': 'company_stage', 'description': 'venture stage of the company, if applicable', 'type': 'string'},
    {'key': 'more_company_info', 'description': 'an array. any company information in the listing not otherwise covered by company_goal, company_status, company_stage, company_description, industry or location', 'type': 'array'},
    {'key': 'employment_type', 'description': 'full-time, part-time, contract, or as otherwise described', 'type': 'string'},
    {'key': 'remote_or_local_details', 'description': 'details about the remote, local, hybrid or otherwise work arrangement as described', 'type': 'string'},
    {'key': 'job_title', 'description': 'job title for the position. Use the singular tense', 'type': 'string'},
    {'key': 'job_description', 'description': 'description of the job as described in the job post', 'type': 'string'},
    {'key': 'job_requirements', 'description': 'an array of the specific job requirements, listed in the job posting', 'type': 'array'},
    {'key': 'job_soft_skills', 'description': 'an array of any soft skills required by the job, as outlined in the posting', 'type': 'array'},
    {'key': 'product_description', 'description': 'a description of the product that job is related to, if any', 'type': 'string'},
    {'key': 'tech_stack', 'description': 'an array. It is list of the names of technologies used by the company. This can include programming languages, frameworks, libraries, databases, and other tools.', 'type': 'array'},
    {'key': 'application_process', 'description': 'any description of the application processes that the person applying will undergo', 'type': 'string'},
    {'key': 'contact_email', 'description': 'a single email. the contact email provided in the job post. if multiple emails are presented, add the additional as an item in the additional notes array', 'type': 'string'},
    {'key': 'application_url', 'description': 'a single url. The url used to apply for the job. information about the company other than the job listing should be placed in the information_urls key', 'type': 'string'},
    {'key': 'information_urls', 'description': 'an array. if the posting states that more information about the company or the job is available at a URL other than the job posting, recored those urls in the array here', 'type': 'array'},
    {'key': 'additional_notes', 'description': 'an array. any additional information about the company, role or position, not covered by the other keys', 'type': 'array'},
    {'key': 'compensation', 'description': 'any compensation and/or benefits described in the job post', 'type': 'string'}
]
