# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_chatbot/02_search.ipynb.

# %% auto 0
__all__ = ['month', 'postsTableName', 'conn', 'cursor', 'format_job_result', 'format_results', 'search']

# %% ../nbs/09_chatbot/02_search.ipynb 3
from .keys import keys

def format_job_result(job_listing):
    job = {}
    
    for key in keys:
        if key in job_listing:
            job[key] = job_listing[key]

    return job

# %% ../nbs/09_chatbot/02_search.ipynb 4
def format_results(results):
    formatted_results = []

    for job_listing in results:
        job = format_job_result(job_listing[0])

        formatted_results.append(job)

    return formatted_results


# %% ../nbs/09_chatbot/02_search.ipynb 7
import psycopg2

month = "july"
postsTableName = "posts_" + month

conn = psycopg2.connect("dbname=Bumpant user=Bumpant password=ampegskb")
cursor = conn.cursor()

def search(requirements):
    initial_results = {}

    for key in requirements.keys():
        query = f"SELECT row_to_json({postsTableName}) FROM {postsTableName} WHERE {key} = '{requirements[key]}' LIMIT 40;"

        cursor.execute(query)

        results = cursor.fetchall()

        formatted_results = format_results(results)

        initial_results[key] = formatted_results
        
        conn.commit()

    return initial_results

search({
    "location": "San Francisco"
})

