# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_pipeline-scrape/04-1_determine_data_format.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_pipeline-scrape/04-1_determine_data_format.ipynb 2
# def split_list(listStr:str):
    # ask the llm to return a 
