# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utility.ipynb.

# %% auto 0
__all__ = ['saveJSON', 'loadJSON']

# %% ../nbs/utility.ipynb 2
import json

def saveJSON(filename, posts):
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(posts, f, ensure_ascii=False, indent=4)

def loadJSON(filename):
    posts = False
    try: 
        with open(filename, 'r', encoding='utf-8') as f:
            posts = json.load(f)
    finally:
        return posts
