# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utility.ipynb.

# %% auto 0
__all__ = ['saveJSON', 'loadJSON', 'getResponse']

# %% ../nbs/utility.ipynb 2
import json

def saveJSON(filename, posts):
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(posts, f, ensure_ascii=False, indent=4)

def loadJSON(filename):
    posts = False
    try: 
        with open(filename, 'r', encoding='utf-8') as f:
            posts = json.load(f)
    finally:
        return posts

# %% ../nbs/utility.ipynb 4
import os
import openai

# openai.api_base = "https://openrouter.ai/api/v1"
openai.api_key = os.environ.get('OPENAI_API_KEY')

def getResponse(text: str):
    response = openai.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": text}],
    )

    result = {
        "input_text": text,
        "text": response.choices[0].message.content
    }

    return result
