# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_pipeline-scrape/00_init.ipynb.

# %% auto 0
__all__ = ['url', 'dataLocation', 'month', 'postsTableName']

# %% ../nbs/03_pipeline-scrape/00_init.ipynb 2
url = "https://news.ycombinator.com/item?id=41129813"
dataLocation = "currentData/"
month = "august"
postsTableName = "posts_" + month
